# Generated by Django 2.0.3 on 2018-04-08 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_library_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersongs',
            name='user',
        ),
    ]
