# Generated by Django 2.0.3 on 2018-04-08 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_library_app', '0002_remove_usersongs_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersongs',
            name='song',
        ),
    ]
