# Generated by Django 2.0.3 on 2018-04-08 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_library_app', '0003_remove_usersongs_song'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSongs',
        ),
    ]
