# Generated by Django 2.0.3 on 2018-04-08 11:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_library_app', '0004_delete_usersongs'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
