# Generated by Django 2.0.3 on 2018-04-08 12:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_library_app', '0006_auto_20180408_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
