# Generated by Django 2.0.3 on 2018-04-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_library_app', '0008_auto_20180409_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='Bio',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='City',
            new_name='city',
        ),
        migrations.AddField(
            model_name='album',
            name='album_info',
            field=models.TextField(blank=True),
        ),
    ]
