# Generated by Django 2.0.3 on 2018-04-16 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_library_app', '0009_auto_20180409_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='user',
            new_name='owner',
        ),
    ]
