# Generated by Django 2.0.3 on 2018-04-16 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_library_app', '0010_auto_20180416_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='owner',
            new_name='owners',
        ),
    ]
