# Generated by Django 2.0.3 on 2018-04-16 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_library_app', '0011_auto_20180416_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='owners',
        ),
        migrations.AddField(
            model_name='playlist',
            name='owner',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='sharing',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
