# Generated by Django 2.0.3 on 2018-04-30 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_library_app', '0012_auto_20180416_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='sharing',
            new_name='user',
        ),
    ]
