# Generated by Django 2.0.3 on 2018-06-19 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_library_app', '0013_auto_20180430_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='whose_album', to='music_library_app.Artist'),
            preserve_default=False,
        ),
    ]
