# Generated by Django 2.0.3 on 2018-06-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_library_app', '0014_album_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='dauration',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
